### ISSUE TITLE
object key with point

### ISSUE THREAD

**Issue by grachet** [cape-io/lodash-clean#1]
hy,

without options when i clean an object with a key like "nathan.drake@gmail.com"
{nathan:{drake@gmail: {com: {…}}}}

Is there a way to prevent that ?

**Comment by webmasterkai** [comment]
I will add some tests for this and see why it’s happening.

**Comment by webmasterkai** [comment]
Added test, fixed, published version 2.1.0 to npm. Thanks for your input!

**Comment by grachet** [comment]
thanks you are really reactive
